package com.peihua.genui.a2a.core

import kotlinx.serialization.Serializable

/** Identifies the sender of a [Message]. */
enum class Role {
    /** The message originated from the user (i.e., the A2A client). */
    USER,

    /** The message originated from the agent (i.e., the A2A server). */
    AGENT,
}

@Serializable
data class Message(
    /**Specifies the sender of the message, either [Role.user] or [Role.agent].**/
    val role: Role,

    /** A list of content [Part]s that make up the message body.
     *
     * A message can be composed of multiple parts of different types
     * (e.g., text, files, structured data).*/
    val parts: List<Part>,

    /** Optional metadata for extensions, as a map where the key is an
     * extension-specific identifier.*/
    val metadata: Map<String, Any?>?,

    /** Optional list of URIs for extensions that are relevant to this message.*/
    val extensions: List<String>?,

    /** Optional list of other task IDs that this message references for
     * additional context.*/
    val referenceTaskIds: List<String>?,

    /** A unique identifier for this message, typically a UUID, generated by the
     * sender.*/
    val messageId: String,

    /** The ID of the task this message belongs to.
     *
     * This can be omitted for the initial message in a new task interaction.*/
    val taskId: String?,

    /** An identifier used to group related messages and tasks, such as within
     * a single conversation or session.*/
    val contextId: String?,

    /** The type discriminator for this object, always 'message'.*/
    val kind: String = "message",
) {
}