package com.peihua.genui.a2a.core

import kotlinx.serialization.Serializable

@Serializable
data class Task(
    /** A unique identifier (e.g., UUID) for the task.
     *
     * This ID is typically generated by the server when a new task is created.
     **/
    val id: String,

    /** A server-generated unique identifier (e.g., UUID) for grouping related
     * tasks or interactions, forming a conversation context.*/
    val contextId: String,

    /** The current status of the task, including its state and any associated
     * message.*/
    val status: TaskStatus,

    /* * An optional list of [Message] objects representing the conversation
     * history of the task.*/
    val history: List<Message>?,

    /** An optional collection of [Artifact]s produced by the agent during the
     * task's execution.*/
    val artifacts: List<Artifact>?,

    /** Optional metadata for extensions, as a map where the key is an
     * extension-specific identifier.*/
    val metadata: Map<String, Any?>?,

    /** The timestamp of the last update to the task, in milliseconds since the
     * Unix epoch.*/
    val lastUpdated: Int?,

    /** The type discriminator for this object, always 'task'.*/
    val kind: String = "task",
)

@Serializable
data class TaskStatus(
    /** The current state in the task's lifecycle.*/
    val state: TaskState,

    /** An optional, human-readable [Message] providing more details about the
     * current status (e.g., an error message or a prompt for input).*/
    val message: Message?,

    /** The timestamp when this status was recorded, in milliseconds since the
     * Unix epoch.*/
    val timestamp: String?,
)
@Serializable
enum class TaskState {
    /** The task has been received by the server but not yet started. */
    SUBMITTED,

    /** The agent is actively processing the task. */
    WORKING,

    /** The task is paused, awaiting further input from the client. */
    INPUT_REQUIRED,

    /** The task has been successfully completed by the agent. */
    COMPLETED,

    /** The task was canceled, typically by a client request. */
    CANCELED,

    /** The task failed due to an error during execution. */
    FAILED,

    /** The task was rejected by the agent before execution began (e.g., due to
     * invalid parameters or permissions). */
    REJECTED,

    /** The task cannot proceed without additional authentication or
     * authorization. */
    AUTH_REQUIRED,

    /** The task is in an unknown or indeterminate state. */
    UNKNOWN,
}

/** Represents a file, data structure, or other resource generated by an agent
 * during a [Task].*/
@Serializable
data class Artifact(
    /** A unique identifier for this artifact within the scope of the task.*/
    val artifactId: String,

    /** An optional, human-readable name for the artifact.*/
    val name: String?,

    /** An optional, human-readable description of the artifact's content or
     * purpose.*/
    val description: String?,

    /** A list of [Part] objects that constitute the content of the artifact.*/
    val parts: List<Part>,

    /** Optional metadata for extensions.*/
    val metadata: Map<String, Any?>?,

    /** Optional list of URIs for extensions that are relevant to this artifact.*/
    val extensions: List<String>?,
) {

}